-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME,  B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
# BOOK_SALES는 이 분석의 핵심 출발점
# BOOK → AUTHOR 경로로 조인해야만 저자 정보를 가져올 수 있음