-- 코드를 입력하세요
SELECT DATE_FORMAT(t.dt, '%Y-%m-%d') AS SALES_DATE, t.PRODUCT_ID, t.USER_ID, t.SALES_AMOUNT
FROM (SELECT DATE(ONLINE_SALE.SALES_DATE) AS dt, PRODUCT_ID, USER_ID, SALES_AMOUNT
      FROM ONLINE_SALE
      WHERE ONLINE_SALE.SALES_DATE >= '2022-03-01' AND ONLINE_SALE.SALES_DATE <  '2022-04-01'
      UNION ALL

      SELECT DATE(OFFLINE_SALE.SALES_DATE) AS dt, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
      FROM OFFLINE_SALE
      WHERE OFFLINE_SALE.SALES_DATE >= '2022-03-01' AND OFFLINE_SALE.SALES_DATE <  '2022-04-01') AS t

ORDER BY t.dt ASC, t.PRODUCT_ID ASC, t.USER_ID ASC;
