#Language: MySQL

SELECT c.COMPANY_CODE, c.FOUNDER,
       COUNT(DISTINCT lm.LEAD_MANAGER_CODE) AS LEAD_MANAGERS,
       COUNT(DISTINCT sm.SENIOR_MANAGER_CODE) AS SENIOR_MANAGERS,
       COUNT(DISTINCT m.MANAGER_CODE) AS MANAGER,
       COUNT(DISTINCT e.EMPLOYEE_CODE) AS EMPLOYEES
FROM COMPANY AS c
LEFT JOIN LEAD_MANAGER AS lm ON lm.COMPANY_CODE = c.COMPANY_CODE
LEFT JOIN SENIOR_MANAGER AS sm ON sm.COMPANY_CODE = c.COMPANY_CODE
LEFT JOIN MANAGER AS m ON m.COMPANY_CODE = c.COMPANY_CODE
LEFT JOIN EMPLOYEE AS e ON e.COMPANY_CODE = c.COMPANY_CODE
GROUP BY c.COMPANY_CODE,c.FOUNDER
ORDER BY c.COMPANY_CODE;
