-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, u.GENDER AS GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE s
JOIN USER_INFO u
ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE), u.GENDER
ORDER BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE), u.GENDER;