-- 코드를 입력하세요
# LEFT JOIN + IS NULL을 이용해야만 출력 가능
# (INNER) JOIN으로는 출력 불가능
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID;