-- 코드를 작성해주세요
SELECT 
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 2), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;

# 정렬은 숫자 합계로 해야하기 때문에 TOTAL_DISTANCE는 안된다 (문자열이므로)