SELECT 
    YEAR(os.SALES_DATE) as YEAR,
    MONTH(os.SALES_DATE) as MONTH,
    COUNT(DISTINCT os.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) / 
          (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) as PUCHASED_RATIO
FROM ONLINE_SALE os
JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;