-- 코드를 작성해주세요
#IF 중첩 사용
SELECT ID, IF(SIZE_OF_COLONY <= 100, 'LOW',
              IF(SIZE_OF_COLONY <= 1000, 'MEDIUM', 'HIGH')) AS SIZE
FROM ECOLI_DATA
ORDER BY ID;

# CASE WHEN
# SELECT ID, CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
#                 WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
#                 ELSE 'HIGH' END AS SIZE
# FROM ECOLI_DATA
# ORDER BY ID;

# ELT() + FIELD() 사용
# SELECT 
#  ID,
#  ELT(
#    FIELD(
#      SIZE_OF_COLONY <= 100, TRUE,
#      SIZE_OF_COLONY <= 1000, TRUE
#    ),
#    'LOW', 'MEDIUM', 'HIGH'
#  ) AS SIZE
# FROM ECOLI_DATA
# ORDER BY ID;


