-- 코드를 입력하세요
SELECT MEMBER_PROFILE.MEMBER_NAME, 
       REST_REVIEW.REVIEW_TEXT, 
       DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
INNER JOIN MEMBER_PROFILE 
      ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE REST_REVIEW.MEMBER_ID = (SELECT MEMBER_ID
                               FROM REST_REVIEW
                               GROUP BY MEMBER_ID
                               ORDER BY COUNT(REVIEW_ID) DESC
                               LIMIT 1)
ORDER BY REST_REVIEW.REVIEW_DATE, REST_REVIEW.REVIEW_TEXT;