-- 코드를 작성해주세요
SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN  (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
       FROM FISH_INFO
       WHERE LENGTH IS NOT NULL
       GROUP BY FISH_TYPE) AS MAX_FISH
ON MAX_FISH.FISH_TYPE = fi.FISH_TYPE
AND MAX_FISH.MAX_LEN = fi.LENGTH
JOIN FISH_NAME_INFO AS fni
ON fni.FISH_TYPE = fi.FISH_TYPE
ORDER BY fi.ID ASC;
       