SELECT COUNT(*) AS FISH_COUNT, MAX(IF(LENGTH IS NULL, NULL, LENGTH)) AS MAX_LENGTH, FISH_TYPE
FROM (
  SELECT 
    FISH_TYPE,
    CASE
      WHEN LENGTH IS NULL THEN NULL
      WHEN LENGTH <= 10 THEN 10
      ELSE LENGTH
    END AS LENGTH
  FROM FISH_INFO
) AS adjusted_fish
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC;
